/*
 * Copyright 1997-2007 Sun Microsystems, Inc. All rights reserved.
 * 
 */

package org.apache.jasper;

/**
 * Base class for all exceptions generated by the JSP engine. Makes it
 * convienient to catch just this at the top-level. 
 *
 * @author Anil K. Vijendran
 */
public class JasperException extends javax.servlet.ServletException {
    
    public JasperException(String reason) {
	super(reason);
    }

    /**
     * Creates a JasperException with the embedded exception and the reason for
     * throwing a JasperException
     */
    public JasperException (String reason, Throwable exception) {
   	super(reason, exception);
    }

    /**
     * Creates a JasperException with the embedded exception
     */
    public JasperException (Throwable exception) {
   	super(exception);
    }
}
